name: Deploy Lambda

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'lambda/**'   # só roda se mexer na pasta lambda

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: lambda

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt -t package

      - name: Copy source code
        run: |
          cp -r src package/
          cp lambda_function.py package/

      - name: Create zip
        run: |
          cd package
          zip -r ../lambda.zip .

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name ingest_job \
            --zip-file fileb://lambda.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}